---
title: "Mixture Modeling Paper Results"
author: "Sarah Sullivan"
date: "March 8, 2017"
output: word_document
---

```{r set_knitr_chunk_options, echo = F, warning=F, message=F}
rm(list = ls())

library(knitr)
library(markdown)
opts_chunk$set(message=FALSE, echo = F,
               warning = F,fig.height = 5, fig.width = 10, tidy = F)

#Work
#opts_knit$set(root.dir = "C:/Users/ntdintern/Google Drive/Sarah Sullivan/Code")
#School
#opts_knit$set(root.dir = "H:/TFGH/Code")
#Laptop
opts_knit$set(root.dir = "/Users/sarahsullivan/Documents/SullivanDocs/Rwd/cutoff/")
```

```{r loadfunctions, echo=F}
source("./Cutoff_Algorithm.R")
```


#Example 1
```{r example1, echo=T}

examp1<-read.csv(file="/Users/sarahsullivan/Documents/SullivanDocs/Rwd/cutoff/ex1.csv", colClasses=c("NULL", NA, NA))

hist(examp1$data, breaks=100, main="", xlab="Optical Density")
dens1<-density(examp1$data)
plot(dens1, main="", xlab="Optical Density")

#fitloopsobject1<-fitloops(datawithids=examp2)
  #might not run due to 5 component solution not being easily optimized, if it doesn't run either load the full file, or run fitloopsobject1<-fitloops(datawithids=examp2,maxcp=4): 
load(file="/Users/sarahsullivan/Documents/SullivanDocs/Rwd/cutoff/ex1fitloops")

bicgraph(fitobj=fitloopsobject1, title="")

modelpickobject1<-modelpick(fitloopsobject1)

rawuncertgraph(modelpickobject1, title="", xlab="Optical Density")
rawdistgraph(modelpickobject1, title="", xlab="Optical Density")
rawhistcuts(modelpickobject1, title="", xlab="Optical Density")

cutoffobject1<-cutoff(modelpickobj = modelpickobject1, newcertlevel = 0.85)

cutuncertgraph(cutobj = cutoffobject1, title="", xlab="Optical Density")
cutdistgraph(cutobj = cutoffobject1, title="", xlab="Optical Density")

summaryobject1<-summaryout(cutobj = cutoffobject1)
summaryobject1$outtab

```

#Example 2

```{r example2, echo=T}

examp2<-read.csv(file="/Users/sarahsullivan/Documents/SullivanDocs/Rwd/cutoff/ex2.csv", stringsAsFactors = F, colClasses=c("NULL", NA, NA))

hist(examp2$data, breaks=100, main="", xlab="Optical Density")
dens2<-density(examp2$data)
plot(dens2, main="", xlab="Optical Density")

fitloopsobject2<-fitloops(datawithids = examp2)

bicgraph(fitobj = fitloopsobject2, title="")

modelpickobject2<-modelpick(fitobj = fitloopsobject2)

rawuncertgraph(modelpickobj = modelpickobject2, title="", xlab="Optical Density")
rawdistgraph(modelpickobj = modelpickobject2, title="", xlab="Optical Density")
rawhistcuts(modelpickobj = modelpickobject2, title="", xlab="Optical Density")

cutoffobject2<-cutoff(modelpickobj = modelpickobject2, cutcomp = 1, newcertlevel = 0.85)

cutuncertgraph(cutobj = cutoffobject2, title="", xlab="Optical Density")
cutdistgraph(cutobj = cutoffobject2, title="", xlab="Optical Density")

summaryobject2<-summaryout(cutobj = cutoffobject2)
summaryobject2$outtab
```

